import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
  route('search', 'routes/search.tsx'),
  route('search/suggest', 'routes/search.suggest.tsx'),
  route('flows', 'routes/flows.tsx'),
  route('network', 'routes/network.tsx'),
  route('trends', 'routes/trends.tsx'),
  route('map', 'routes/map.tsx'),
  route('competition', 'routes/competition.tsx'),
  route('analytics', 'routes/analytics.tsx'),
  route('companies', 'routes/companies.tsx'),
  route('companies.csv', 'routes/companies.csv.tsx'),
  route('companies/:eik', 'routes/company.tsx'),
  route('authorities', 'routes/authorities.tsx'),
  route('authorities.csv', 'routes/authorities.csv.tsx'),
  route('authorities/:eik', 'routes/authority.tsx'),
  route('contracts', 'routes/contracts.tsx'),
  route('contracts.csv', 'routes/contracts.csv.tsx'),
  route('contracts/:id.json', 'routes/contract.json.tsx'),
  route('contracts/:id', 'routes/contract.tsx'),
  route('methodology', 'routes/methodology.tsx'),
  route('accessibility', 'routes/accessibility.tsx'),
  route('privacy', 'routes/privacy.tsx'),
  route('impressum', 'routes/impressum.tsx'),
  route('robots.txt', 'routes/robots.tsx'),
  route('sitemap.xml', 'routes/sitemap.tsx'),
  route('sitemap-pages.xml', 'routes/sitemap-pages.tsx'),
  route('sitemap-authorities.xml', 'routes/sitemap-authorities.tsx'),
  route('sitemap-companies.xml', 'routes/sitemap-companies.tsx'),
  route('sitemap-contracts.xml', 'routes/sitemap-contracts.tsx'),
] satisfies RouteConfig;
