#!/usr/bin/env node
// One-time generator for the Bulgaria region (NUTS3) map geometry used by /map.
// Source: GISCO NUTS 2021, 20M resolution, EPSG:4326 (© EuroGeographics). Filters the 28 BG NUTS3
// features, applies a plain equirectangular projection fitted to the BG bbox (x scaled by cos(midLat)
// so the country is not horizontally stretched), rounds to 0.1 user units, and writes a static SVG
// path per region keyed by NUTS_ID. Output: apps/web/app/lib/bg-region-geometry.ts (committed; no runtime dep).
//
// Run: node scripts/build-geo.mjs   (then `pnpm exec prettier --write apps/web/app/lib/bg-region-geometry.ts`)

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC =
  'https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_20M_2021_4326_LEVL_3.geojson';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(root, 'apps/web/app/lib/bg-region-geometry.ts');
const SCALE = 219; // degrees -> user units; ~1000 wide viewBox for clean rounding

const res = await fetch(SRC, { signal: AbortSignal.timeout(30_000) });
if (!res.ok) throw new Error(`GISCO fetch failed: ${res.status}`);
const gj = await res.json();
const bg = gj.features.filter((f) => String(f.properties.NUTS_ID || '').startsWith('BG'));
if (bg.length !== 28) throw new Error(`expected 28 BG NUTS3 features, got ${bg.length}`);

const eachCoord = (c, cb) =>
  typeof c[0] === 'number' ? cb(c) : c.forEach((x) => eachCoord(x, cb));
let lonMin = Infinity,
  lonMax = -Infinity,
  latMin = Infinity,
  latMax = -Infinity;
for (const f of bg)
  eachCoord(f.geometry.coordinates, ([lon, lat]) => {
    lonMin = Math.min(lonMin, lon);
    lonMax = Math.max(lonMax, lon);
    latMin = Math.min(latMin, lat);
    latMax = Math.max(latMax, lat);
  });
const k = Math.cos((((latMin + latMax) / 2) * Math.PI) / 180);
const px = (lon) => +((lon - lonMin) * k * SCALE).toFixed(1);
const py = (lat) => +((latMax - lat) * SCALE).toFixed(1); // flip Y for SVG
const W = Math.round((lonMax - lonMin) * k * SCALE);
const H = Math.round((latMax - latMin) * SCALE);

const polysOf = (g) => (g.type === 'Polygon' ? [g.coordinates] : g.coordinates);
function pathD(geom) {
  let d = '';
  for (const poly of polysOf(geom))
    for (const ring of poly) {
      ring.forEach(([lon, lat], i) => (d += `${i ? 'L' : 'M'}${px(lon)},${py(lat)}`));
      d += 'Z';
    }
  return d;
}

const regions = bg
  .map((f) => ({ nuts3: f.properties.NUTS_ID, d: pathD(f.geometry) }))
  .sort((a, b) => a.nuts3.localeCompare(b.nuts3));

const body = `// Generated by scripts/build-geo.mjs from GISCO NUTS 2021, 20M (© EuroGeographics,
// https://ec.europa.eu/eurostat/web/gisco). Do not edit by hand; rerun the script to regenerate.
// One SVG path per Bulgarian region, keyed by NUTS3 id (joins @sigma/config BG_REGIONS). Names and
// macro-region grouping live in BG_REGIONS, not here, so there is a single source of truth.

export interface RegionShape {
  nuts3: string;
  d: string;
}

export const BG_MAP: { viewBox: string; regions: RegionShape[] } = {
  viewBox: '0 0 ${W} ${H}',
  regions: ${JSON.stringify(regions)},
};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${regions.length} regions, viewBox 0 0 ${W} ${H}, ${body.length} bytes`);
