/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.dev.jsonc --include-runtime=false --env-interface=DevEnv src/dev-bindings.d.ts` (hash: 4c3ee8785f64276d6e30dac1380dea6d)
interface __BaseEnv_DevEnv {
  DECLARATIONS_CORPUS: R2Bucket;
  DB: D1Database;
  REGISTRY_API_BASE_URL: 'https://api-sigma-cr.registryagency.bg';
  REGISTRY_PORTAL_URL: 'https://portal.registryagency.bg/CR/api/Applications/Entries';
  SIGMA_D1_ID: '713b98fa-6ab5-45f3-81c4-119f4c0907d6';
  SIGMA_D1_NAME: 'sigma-dev';
  SIGMA_SHIP_ENV: 'dev';
  DECLARATIONS_BUCKET: 'sigma-declarations-dev';
  DECLARATIONS: DurableObjectNamespace<import('./index').DeclarationContainer>;
  REGISTRY: Workflow<Parameters<import('./index').RegistryWorkflow['run']>[0]['payload']>;
  DECLARATIONS_RUN: Workflow<
    Parameters<import('./index').DeclarationsWorkflow['run']>[0]['payload']
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
    durableNamespaces: 'DeclarationContainer';
  }
  interface Env extends __BaseEnv_DevEnv {}
}
interface DevEnv extends __BaseEnv_DevEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'REGISTRY_API_BASE_URL'
      | 'REGISTRY_PORTAL_URL'
      | 'SIGMA_D1_ID'
      | 'SIGMA_D1_NAME'
      | 'SIGMA_SHIP_ENV'
      | 'DECLARATIONS_BUCKET'
    >
  > {}
}
declare module '*.sql' {
  const value: string;
  export default value;
}
